### ISSUE TITLE
v1.04.x Tracking List

### ISSUE THREAD

**Issue by mattlag** [mattlag/Glyphr-Studio#221]
Boolean Features
- [x] Continue to fix Combine edge cases

Feature Creep
- [x] Transient warning messages
- [x] Use opacity for kerning display
- [x] export font option to flatten glyphs - UI Options
- [x] export font option to flatten glyphs - Async feedback

**Comment by mattlag** [comment]
Closing out the milestone!
